# slide config for dev
---
duration: 1000
slides:
  - type: DrivingMap
    title: 'Mark & Yoojin Summer 2021!'
    photosBucket: display-photos
    photosDir: test
    stops:
      - location: San Francisco, CA
        labelPosition: 'west'
        labelText: 'Start: 8/6'
        type: major
        labelMarkerMargin: 12
      - location: Truckee, CA
        locationText: Truckee
        labelPosition: 'northwest'
        startDate: 8/6
        type: minor
      - location: Winnemucca, NV
        locationText: Winnemucca
        labelPosition: 'north'
        startDate: 8/6
        type: minor
      - location: Salt Lake City, UT
        locationText: SLC
        labelPosition: 'south'
        startDate: 8/7
        type: minor
      - location: Denver, CO
        locationText: Denver
        labelPosition: 'northeast'
        startDate: 8/8
        endDate: 8/28
        type: major
      - location: Kuttawa, KY
        locationText: Kuttawa
        labelPosition: 'southwest'
        startDate: 8/28
        type: minor
      - location: Henderson, KY
        locationText: Henderson
        labelPosition: 'north'
        startDate: 8/29
        type: minor
        labelMarkerMargin: 12
      - location: Prospect, KY
        locationText: Louisville
        labelPosition: 'east'
        startDate: 8/29
        endDate: 9/3
        type: major
        labelMarkerMargin: 10
      - location: Nashville, TN
        locationText: Nashville
        labelPosition: 'east'
        startDate: 9/3
        endDate: 9/11
        type: major
      - location: Dallas, TX
        locationText: Dallas
        labelPosition: 'northwest'
        startDate: 9/11
        type: minor
      - location: Waco, TX
        locationText: Waco
        labelPosition: 'east'
        startDate: 9/12
        type: minor
      - location: Austin, TX
        locationText: Austin
        labelPosition: 'south'
        startDate: 9/12
        endDate: 10/2
        type: major
      - location: White Sands, NM
        locationText: White Sands NP
        labelPosition: 'east'
        startDate: 10/2
        type: minor
      - location: Flagstaff, AZ
        locationText: Flagstaff
        labelPosition: 'northeast'
        startDate: 10/3
        endDate: 10/8
        type: major
        labelMarkerMargin: 6
      - location: Sedona, AZ
        locationText: Sedona
        labelPosition: 'west'
        startDate: 10/3
        type: minor
        labelMarkerMargin: 10
      - location: Grand Canyon South Rim Park Headquarters
        locationText: Grand Canyon NP
        labelPosition: 'west'
        startDate: 10/8
        type: minor
      - location: Phoenix, AZ
        locationText: Phonenix
        labelPosition: 'east'
        startDate: 10/8
        type: minor
      - location: San Diego, CA
        locationText: San Diego
        labelPosition: 'southwest'
        startDate: 10/9
        endDate: 10/16
        type: major
      - location: Los Angeles, CA
        locationText: Los Angeles
        labelPosition: 'southwest'
        startDate: 10/10
        type: minor
      - location: Arroyo Grande, CA
        locationText: Arroyo Grande
        labelPosition: 'west'
        startDate: 10/17
        type: major
        endDate: 10/22
      - location: San Francisco, CA
        labelPosition: 'east'
        labelText: 'End: 10/22'
        type: major
        labelMarkerMargin: 12